version: '3'
services:
  nextjs:
    container_name: frontend
    restart: always
    build: ./
    working_dir: /frontend
    volumes:
      - /pages
    ports:
      - '3000:3000'
    #command:
      #["npm run dev"]
    stdin_open: true
    depends_on: 
      - express
 
  #nest:
    #build: ./
    #working_dir: /
    #ports:
      #- '3003:3003'
    #environment:
      #PORT: 3003
    #command:
      #["npm run start"]
  
  mysql-db:
   container_name: database
   restart: always 
   image: mysql:5.7
   ports:
    - "3306:3306"
   environment:
    MYSQL_DATABASE: "seaniak"
    MYSQL_PASSWORD: "password"
    MYSQL_ROOT_PASSWORD: "password"    
    MYSQL_USER: "dev"

  express:
    container_name: api
    restart: always
    build: ./
    working_dir: /express-api
    ports:
      - '3003:3003'
    stdin_open: true
    depends_on: 
      - mysql-db