version: '3'
services:
  #nextjs:
    #container_name: frontend
    #restart: always
    #build: ./frontend/pages
    #command: npm run dev
    #working_dir: /frontend
    #volumes:
      #- /pages
    #ports:
      #- '3000:3000'
    #stdin_open: true
    #depends_on: 
      #- express
    #links:
      #- mysql-db
 
  mysql-db:
   container_name: database
   restart: always 
   image: mysql:5.7
   ports:
    - '3306:3306' 
   environment:
    MYSQL_DATABASE: "seaniak"
    MYSQL_PASSWORD: "password"
    MYSQL_ROOT_PASSWORD: "password"    
    MYSQL_USER: "dev"

  express:
    container_name: api
    restart: always
    build: ./express-api
    command: npm run dev
    #working_dir: /express-api
    ports:
      - '3003:3003'
    stdin_open: true
    depends_on: 
      - mysql-db