version: '3'
services:
  nextjs:
    container_name: frontend
    restart: always
    build: ./
    command: npm run dev
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
    stdin_open: true
    #links:
      #- mysql-db
      #- express
    depends_on: 
      - express

  mysql-db:
    container_name: database
    restart: always
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'seaniak'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'dev'

  express:
    container_name: api
    restart: always
    build: ./
    command: npm run dev
    ports:
      - '3003:3003'
    environment:
      PORT: 3003
    stdin_open: true
